### ISSUE TITLE
Marketplace listing - small issues

### ISSUE THREAD

**Issue by kristoferlund** [hypercerts-org/hypercerts-app#111]
### Listing created as ETH is displayed as WETH in buy dialog.

Created as:
 
![Screenshot 2024-07-12 at 10 10 31](https://github.com/user-attachments/assets/55f65be5-2273-4016-96c6-ee9b5f404596)

Displayed as:

![image](https://github.com/user-attachments/assets/3cf8b3b0-5f18-4567-923d-fca9f0745e50)

### Units should be formatted uniformly in all marketplace components

![image](https://github.com/user-attachments/assets/9b7d0fe5-00d8-4325-b6de-4b813e74119a)

- Use `<FormattedUnits>` component

### Currencies should be formatted uniformly 

Marketplace listing created as "1 ETH" is displayed like this: 

![image](https://github.com/user-attachments/assets/d4e2558f-d8b0-46fe-98c8-1567467988b7)

**Comment by bitbeckers** [comment]
Fixed in #166
