### ISSUE TITLE
[UI] Transfer a fraction

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts-app#121]
As a user, I want to be able to quickly transfer an hypercert, so that I can distribute fractions to other users.

* The transfering of an hypercerts is a function of the [TransferRestrictions](https://github.com/hypercerts-org/hypercerts/blob/7671d06/sdk/src/types/hypercerts.ts#L9). The app should check on the transfer restriction.
* If the TransferRestriction prevents the transfer, the icon should be grayed out. A notification should inform the user.

Ref: [Transfer wireframe](https://www.figma.com/board/wJAHoBKEFgM0Wur0cXZdqX/Hypercerts-app-1.2?node-id=589-1191&t=WV7geS3tmgRXVbt0-4)

**Comment by holkexyz** [comment]
1. The container with the title and the new buttons is not stretching (see image)
2. When we open the meatball menu, I prefer not to show the icons (just text feels cleaner)
3. (nice-to-have) I would prefer the send symbol to be a little smaller

![Image](https://github.com/user-attachments/assets/73d951d2-d885-4a0f-b7f3-53ce39b25c3f)

**Comment by holkexyz** [comment]
4. On mobile I would top-align the meatball menu

![Image](https://github.com/user-attachments/assets/58d87929-5f98-449e-9e72-85fe5a96e06b)

**Comment by holkexyz** [comment]
5. There should always be a bit of distance between the symbol and the title
![Image](https://github.com/user-attachments/assets/e43a18d6-1985-41cc-8303-15d4b88c3fa7)

**Comment by bitbeckers** [comment]
In #296
