### ISSUE TITLE
[UI] Split a fraction

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts-app#122]
As a user, I want to be able to split an hypercert fraction, so that I can transfer or sell a full fraction while retaining some.

* Splitting of an fraction requires an array of new fraction balances that totals to the original amount of fractions

Ref: [Split fraction wireframe](https://www.figma.com/board/wJAHoBKEFgM0Wur0cXZdqX/Hypercerts-app-1.2?node-id=589-1190&t=WV7geS3tmgRXVbt0-4)

**Comment by holkexyz** [comment]
I like it!

UI feedback:
1. (nice-to-have) It is confusing that I can click on +25% even if 25% aren't left to be allocated from the remaining units. Can we gray those out?
2. The remaining units are a bit confusing. Suggestion: Let's call them "Fraction 1 (remaining units)". Then it makes more sense to add more fractions to that.
3. The distribution bar is nice, but it doesn't make sense if we calculate the remaining units automatically. 100% is always distributed if I understood it correctly.
4. Let's add a line "Total Units of Fraction: XXXX" above the Remaining Units
5. Let's add a title above the quickadd buttons "Add fraction"

**Comment by bitbeckers** [comment]
In #296
