### ISSUE TITLE
[Explore] Filter hypercerts based on attestation status

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts-app#137]
As an user, I want to be easilty find evaluated/verified hypercerts, so that I can easily impact which projects to fund.

The open action is defaulting to option B from below.
Currently, we're missing the backend to implement C from below. 

From GDoc:

> filter missing for showing only those hypercerts that have been evaluated at least once and/or those that have been positively evaluated
> a. Show all hypercerts
> b. Show only evaluated hypercerts (selected by default)
> c. Show only verified hypercerts

**Comment by bitbeckers** [comment]
FYI, `only evaluation` can be determined by the field `attestations_count` in the graphl on the hypercerts entity. I found filtering on `gte: 1` to give the best results. It's a new field, so wanted to point this out

**Comment by holkexyz** [comment]
implemented on testnet, thanks. 

Follow up task to have only verified here: https://github.com/hypercerts-org/hypercerts-app/issues/186
