### ISSUE TITLE
[create] enforce character limits

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts-app#190]
I just minted a hypercert with a very looooong title :D https://testnet.hypercerts.org/hypercerts/11155111-0xa16DFb32Eb140a6f3F2AC68f41dAd8c7e83C4941-213697326426349355054999253467150436794368

Let's enforce some character limits
- Title: Max. 100 characters
- Description: Max. 5000 characters
- Single work tags: 50 characters
- Single contributor: 50 characters

If it is easy we can also limit the number of work tags to 20.

edit: changed the description limit to 5000 based on comments below

**Comment by bitbeckers** [comment]
@holkexyz agreed on all except for description. 1500 characters is pretty short and I've seen metadata that has a pretty longwinded report on the content of the claim. We can simply truncate the description and have a 'read more' accordeon.

Is the 1500 arbitraty? Would 3000 of 5000 be enough?
