### ISSUE TITLE
[UI] tabs on profile

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts-app#192]
Change the the wording and order: First "Owned" (selected by default), then "Created", then "Claimable". As someone else could look at my profile, it doesn't make sense that it says "by me"

**Comment by bitbeckers** [comment]
In #215

**Comment by bitbeckers** [comment]
On testnet.hypercerts.org

![Image](https://github.com/user-attachments/assets/3ec308bf-c2c1-4198-989b-8047feb5ad9d)
