### ISSUE TITLE
[FE] evaluator tab narrower and more per page

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts-app#194]
1. The evaluator tab is very wide given the content. Let's make the table half the width and keep it centered, i.e. create a max-width for the table.
2. There are only 6 evaluators per page. Let's increase that to 20.

![Image](https://github.com/user-attachments/assets/cf0a2ea9-faf9-4495-b29f-9a7d59bbc1b8)

**Comment by holkexyz** [comment]
Also see: https://github.com/hypercerts-org/hypercerts-app/issues/203

And I edited the above to specify that we only want a narrower max-width on the table to keep the overall max-width consistent

**Comment by bitbeckers** [comment]
![Image](https://github.com/user-attachments/assets/14fe60fc-7f5d-4edb-bd70-9965467cfe09)
