### ISSUE TITLE
[UX] add stepper modal for successful sale

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts-app#196]
After I successfully buy a fraction I just get back to the buy pop-up without any message that it was successful. Let's add a screen that confirms the sale.

![Image](https://github.com/user-attachments/assets/ca915d9c-49fe-4fbe-a209-3671672d0c41)

**Comment by bitbeckers** [comment]
The transaction should follow the same stepper modal as used in the create form, with the link buttons in the bottom linking to 1) transaction and 2) 'Owned by my'

The user can get back to the hypercert view page by closing the modal, so my assumption is that offering a button to that page is redundant.

**Comment by holkexyz** [comment]
@Jipperism drew it on the figjam under marketplace 



![Image](https://github.com/user-attachments/assets/8c7d872d-0e1c-4c66-a5a1-2e9d24099f5e)
