### ISSUE TITLE
[UX] use transaction stepper for listing creation

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts-app#199]
When creating a listing, or generally any transaction, in the app I'm expecting a similar process. The transaction stepper is a very nice feature, but appears to only be implemented in the create form.

#196 adds the stepper to the sale flow, the purpose of this story is to add it to the create listing flow

As there's no transaction to review, the stepper should only have 1 button at the bottom "view listings"

**Comment by Jipperism** [comment]
Ended up adding a close button as well, as that is needed to trigger a reload so the new listing will show up.
