### ISSUE TITLE
[App] Failed to validate allowlist

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts-app#200]
Failed to validate allowlist on Sepolia

**Comment by bitbeckers** [comment]
![Image](https://github.com/user-attachments/assets/c3952e72-4bb1-44b2-b861-93cba06a60f0)

**Comment by bitbeckers** [comment]
- https://stackoverflow.com/questions/76989456/error-failed-to-fetch-rsc-payload-falling-back-to-browser-navigation
- https://github.com/vercel/next.js/issues/48677

**Comment by bitbeckers** [comment]
Limit fixed in https://github.com/hypercerts-org/hypercerts-api/pull/138

App only calls 'validate', this needs to be a POST to store not to validate

**Comment by holkexyz** [comment]
FYI I don't get the error message anymore. When I click on "Create" it shows "Creating" for a second and then returns to the normal pop-up with the "create" button visible
