### ISSUE TITLE
[UI] Mobile view - explore

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts-app#252]
1. On mobile the navigation menu is too wide. Not sure what the best solution is, maybe two rows or something else? @thebeyondr any suggestions?
2. The page navigation buttons are not ideal, maybe we can replace the big buttons with symbols on mobile?
3. The navigation on mobile has still a submenu for create --> hypercert. The create button can lead directly to the "Create hypercert" page

![Image](https://github.com/user-attachments/assets/f386384d-fa90-4cac-b1d6-0424f0fac8eb)

![Image](https://github.com/user-attachments/assets/4d60ec83-b485-4ec3-9af2-6a677126b185)

**Comment by thebeyondr** [comment]
- Updated the filters to be 2 rows
- Removed sub-menu for New hypercert

![explore-mobile](https://github.com/user-attachments/assets/ebbb6546-8c61-4422-a15b-e81d0ef54fa6)

**Comment by holkexyz** [comment]
This is great, thanks
