### ISSUE TITLE
[UI] evaluation on view page

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts-app#253]
On the view page of a hypercert the checkmarks for the evaluations are too far away from the text. 

Suggested solution:
- Have up to two evaluations side by side (responsive design)
- Have a border around each evaluation like the boxes of contributors and owners
- Have a max width of each evaluation like the boxes of contributors and owners

Basically the suggestion is to have it the same as the contributor and owner boxes

![Image](https://github.com/user-attachments/assets/9afd43cc-53c3-43fe-9cf4-6e9194b209b7)

**Comment by bitbeckers** [comment]
Wrapped in #332
