### ISSUE TITLE
[UI] Always show "My hypercerts"

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts-app#254]
Currently "My hypercerts" is only shown in the navbar when a wallet is connected.

Can we always show it and then if no wallet is connected, have a box that says "Please connect your wallet to see your hypercerts" in the style of the boxes that we already have on the profile (see below)?

![Image](https://github.com/user-attachments/assets/4bacdd01-afde-4375-9d26-63f2b9150349)

![Image](https://github.com/user-attachments/assets/5875fff0-870a-4003-9ea5-4027dc28bbbd)

**Comment by thebeyondr** [comment]
![{2CD3ECFB-5A35-4CBA-A832-3D57E214DD11}](https://github.com/user-attachments/assets/67064244-5671-46c6-9da3-2023309fe0d8)

Added UI for this

**Comment by holkexyz** [comment]
Works for now. 

It feels a bit like an unusual UI. At some point I would like to have a separate page that opens and asks the user to connect
