### ISSUE TITLE
Owner-defined collections of hypercerts

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts-app#29]
### Describe the feature you'd like to request

Right now collections are globally defined (we do it manually).
It's be nice for owners to create groups of hypercerts that they own.

### Describe the solution you'd like

In the dashboard, we let users create collections and add/remove hypercerts from them.

### Describe alternatives you've considered

N/A

**Comment by Jipperism** [comment]
Will be implemented in https://github.com/orgs/hypercerts-org/projects/12
