### ISSUE TITLE
[FE] wrap collection title and description in card

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts-app#97]
Give the same clickable experience to collections as to the hypercert cards:

* Render title and description in bordered box
* Float up on hover
* Use same fonts

Example (conceptual):

<img width="633" alt="Screenshot 2024-07-05 at 13 08 30" src="https://github.com/hypercerts-org/hypercert-app/assets/19667964/af5b535c-b688-427b-b806-968b33df18e8">

**Comment by Jipperism** [comment]
Closing in favor of #235
